# ****************************************************************************
# NOTES:
#
# Testing workflow for updating data in data repository.
#
# TODO: Have data update to a specific data-update branch, so we can review  
# the data updates before merging to dev branch.
#
# TODO: schedule updates for every week
#
# TODO: check if any files changed in repo when update runs and only commit/
# push if there were changes
#
# ****************************************************************************

name: Data update

on:
  push:
    branches:
      - data-update

jobs:
  data-update:
    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with: 
        r-version: 4.1.3
  
    - name: Cache R packages
      id: cache
      uses: actions/cache@v2
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-dataupdate
        restore-keys: |
          ${{ runner.os }}-

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        install.packages(c("dplyr", "readr", "cansim"))
      shell: Rscript {0}

    - name: Updating data and cleaning 
      run: |
        source('scripts/R/indicator_9-5-1.R')
      shell: Rscript {0}

    - name: Commit files
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "Add changes"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}



